spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=springstudent
spring.datasource.password=springstudent

#spring.data.rest.base-uri=/magic-api
spring.mvc.servlet.path=/rest
# Use http://localhost:8080/rest/employees

#http://localhost:8080/rest/employees?page=0&size=2&sort=firstName,desc
spring.data.rest.default-page-size=2
